### PR TITLE
Support running the script in a docker compose environment

### PR DESCRIPTION
**Pull request by rudokemper**
This pull request incorporates a series of enhancements and fixes to add docker compose functionality and ensure cross-platform support:

1. Dockerfiles for the main app and for Tileserver-GL, incorporating the main `tileserver-gl` server and a small shell command to listen for the creation of a `config.json` file (representing the culmination of the first part of the script, at which point Tileserver-GL is ready to start).
2. `docker-compose.yml` to handle service orchestration for the main app and `tileserver-gl`.
3. A `run.sh` script to parse input and output flags and pass them to docker compose, as well as handling the shutdown of containers upon script completion.
4. `main.py` (used for Python environment) has been split up into `docker-generate.py` and `docker-tileserver-compile.py`, each of which is feeding a Docker service, preceding and succeeding `tileserver-gl`, respectively. There is some DRY redundancy between `main.py` and these files that could probably be cleaned up in the future. 
5. A `wait_for_tileserver_gl()` function which requests the Tileserver-GL health endpoint to ensure the server is ready.
6. Small fixes to the various functions to get them working for both Docker and Python environments.
7. Optional PORT variable added to `.env` for Tileserver-GL, in case 8080 is occupied.
8. Modified the Readme to reflect the new changes and Docker runtime option.

### CODE REVIEW

**Comment by IamJeffG** [comment]
This is a workflow we want to trigger every time a change detection is made, right?

I will need to think about the right target to deploy this (in google cloud or azure) and we may need to tweak things for that.

**Comment by rudokemper** [comment]
Yes, that is correct: the envisioned workflow is that this script would be triggered every time a new change detection alert message is received by Frizzle.

**Comment by rudokemper** [comment]
I'm inclined to merge this since the Docker compose workflow itself works fine, and we're now looking at a separate batch of work for deployment. I can start an issue for further discussion. Does that sound good?

**Comment by IamJeffG** [comment]
Oh, I can't believe I let this go 3 weeks with no reply!  My apologies.  Yes, go ahead and merge.

**Pull request merged**
